name = "auto-registro"
main = "worker.js"
compatibility_date = "2026-06-16"

[vars]
ALLOWED_ORIGIN = "https://alexraiden.github.io"

[[kv_namespaces]]
binding = "AUTO_REGISTRO_KV"
id = "58551a98658b41ec90e39f2b502fd739"
